name: Build axel on Ubuntu
on:
  workflow_dispatch:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  release:
    types: [released]

jobs:
  build_axel:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          automake \
          autoconf-archive \
          autopoint \
          libtool \
          gettext \
          pkg-config \
          make \
          gcc \
          libssl-dev \
          libc6-dev \
          
          wget \
          git \
          p7zip-full
        #wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.72.tar.gz
        #tar -xzf autoconf-2.72.tar.gz
        #cd autoconf-2.72
        #./configure --prefix=/usr/local
        #make -j$(nproc)
        #sudo make install
        #cd ..
        #rm -rf autoconf-2.72*

    - name: Build axel
      run: |
        wget https://github.com/axel-download-accelerator/axel/releases/download/v2.17.14/axel-2.17.14.tar.gz
        tar -zxvf axel-2.17.14.tar.gz
        cd axel-2.17.14
        ./configure \
          LDFLAGS="-static -Wl,--whole-archive -lpthread -ldl -Wl,--no-whole-archive" \
          LIBS="-static-libgcc -static-libstdc++ -lcrypto -lssl -lnss_files -lnss_dns -lresolv"
        make
        sudo make install

    - name: Collect binaries
      run: |
        mkdir -p artifact
        which axel && cp $(which axel) artifact/
        ldd $(which axel) || true  # Static build should show "not a dynamic executable"

    - name: Create 7z package
      run: |
        7z a axel.7z -r artifact/*

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: axel-binaries
        path: |
          artifact/*
          axel.7z

    - name: Create Release
      if: success()
      uses: ncipollo/release-action@v1
      with:
        tag: axel-ubuntu-latest
        allowUpdates: true
        artifacts: axel.7z
        token: ${{ secrets.GITHUB_TOKEN }}
