name: Build axel
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  release:
    types:
      - released
jobs:
  build_axel:
    permissions:
      contents: write
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4
    - name: Set up msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          base-devel
          gcc
          make
          gettext
          gettext-devel
          autoconf
          automake
          autoconf-archive
          libtool
          pkg-config
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-openssl
          mingw-w64-x86_64-winpthreads-git
          mingw-w64-x86_64-headers
          mingw-w64-x86_64-crt
          mingw-w64-x86_64-openssl-static
          mingw-w64-x86_64-winpthreads-static
        
    - name: Build axel
      shell: msys2 {0}
      run: |
        echo "查找"
        echo $MSYSTEM
        find -type f -name "inet.h"
        echo "查找"
        export CPATH=/mingw64/include
        export LIBRARY_PATH=/mingw64/lib
        wget https://github.com/axel-download-accelerator/axel/releases/download/v2.17.14/axel-2.17.14.tar.gz
        tar -zxvf axel-2.17.14.tar.gz
        cd axel-2.17.14
        ./configure LDFLAGS="-static"
        make

# 注意修改Cygwin路径      
    - name: Copy Files
      run: |
        cd C:\msys64\usr\bin
        cp msys-2.0.dll, msys-ssl-3.dll, msys-crypto-3.dll, msys-z.dll ${{ github.workspace }}\
        cp ${{ github.workspace }}\**\*.exe ${{ github.workspace }}\
 
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: axel
        path: |
          ${{ github.workspace }}\*.exe
          ${{ github.workspace }}\*.dll
          
    - name: Package Release
      run: 7z a axel.7z -r ${{ github.workspace }}\**\*.exe ${{ github.workspace }}\**\*.dll
      
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
          tag: axel-2.17.14
          allowUpdates: true
          artifacts: axel.7z
          token: ${{ secrets.GITHUB_TOKEN }}
